from transformers import set_seed
import nlpaug.augmenter.word as naw

set_seed(3)

zero = [
    "Rain caused cancellation of the event in 1877, so enforcement of the new law had to wait until 1878.",
    "Finally, Slone's fear of AIDS and the mental distress she suffered from this fear were caused by the needle stab.",
    "In the last couple of years I have been working with my fear from darkness.",
    "Infectious diseases or communicable diseases are caused by bacteria, viruses, and parasites.",
    "By far the greatest damage has been caused by the illicit use of the hallucinogens.",
    "The cause for the jump to over 30,000 was the deterioration in the economy triggered by a series of bankruptcies among banks and securities firms.",
    "The environmental and health consequences of the evacuation after the Chernobyl accident.",
    "The Queen has expressed her shock at the devastation caused by the flooding.",
    "Plaintiffs seek compensatory damages for personal injuries, property damage, emotional distress, and expenses resulting from the evacuation after the explosion.",
    "Seasonal and nocturnal migrations cause sleep deprivation in diurnal Swainson's thrush, Catharus ustulatus.",
    "The sheer scale of the death and destruction caused by the 2004 Boxing Day tsunami is impossible to fathom, even five years on.",
    "Tides are caused by the gravitational pull of the moon and sun, and the rotation of the Earth.",
    "The dramatic streaks we see in the sky are caused by particles that incinerate before they hit the ground.",
    "These toxins cause sickness or an unpleasant odor.",
    "A polio outbreak in Nigeria was caused by the vaccine designed to stop it, leaving at least 69 children paralyzed.",
    "The accident caused a traffic snarl on the ever busy bridge leading to diversions to other routes.",
    "Depression is among the top 10 causes of suicide both among doctors as well as nursing professionals.",
    "The shot caused a wound on the left side of the neck which bled profusely."
]

one = [
    "The storm is generated by an upwelling of warmer air, similar to a terrestrial thunderhead.",
    "Colds and flu cause high fevers in babies and toddlers, but with the flu, the fever will last more than one or two days.",
    "The thin F ring on the left of the image shows the perturbations caused by the moon Prometheus.",
    "The variations are caused by stratospheric winds and the chemical production and destruction of ozone.",
    "Most illnesses, including colds and flu, cause a toxic overload that also increases the stress on the kidneys.",
    "The pandemic was caused by the virus Yesinia pestis, better known as The Bubonic Black Plague, which infected the flees on the Black rodents.",
    "The speech caused a conservative combustion on the Internet, but when Wanda visited The Tonight Show a few weeks later to talk about the dinner, she told Jay Leno that she didn't even know about the controversy.",
    "Each time a neuron unleashes its tiny jolt, it needs to replenish its stores of energy for the next spark.",
    "Scientists have revealed how environmental irritants such as air pollution and cigarette smoke which cause coughing in people.",
    "The complication arose from the light irradiation."
]

for j in zero:
    text = j
    for i in range(0, len(one)):
        aug = naw.ContextualWordEmbsAug(model_path = "bert-base-uncased", device = "cpu", action = "substitute")
        print(aug.augment(text)[0])

print("-------")
        
for j in one:
    text = j
    for i in range(0, len(zero)):
        aug = naw.ContextualWordEmbsAug(model_path = "bert-base-uncased", device = "cpu", action = "substitute")
        print(aug.augment(text)[0])

